spring:
  datasource:
    url: jdbc:mysql://centos:3306/crawler-selenium?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 4321red@zz
    driver-class-name: com.mysql.cj.jdbc.Driver

download:
  path: D:\\temp\\download\\